var localData={
            "nav1":{
                "name":"云居寺",
                "logoBox":"images/logo1",
                "introductionText":"云居寺位于北京市房山区大石窝镇，距市区65公里，是北京地区著名的寺院之一。该寺始建于隋朝大业年间,珍藏着大量石经、纸经和木版经，并称“云居寺三绝”。僧人在此刻经千年，历经六朝十六代，刻经1122部、3572卷、14278块，分别藏于石经山九个藏经洞和云居寺地宫之中，堪称世界佛经镌刻之最，赢得了“北京的敦煌”、“石经长城”等美誉。云居寺还完好保存唐塔7座、辽塔5座，有“碑海塔林”之称。1981年在石经山的雷音洞内发掘出两颗佛祖释迦牟尼肉身舍利，是全世界已发现的唯一不是供奉塔里，而是埋在洞里的佛舍利，与八大处的佛牙、法门寺的佛指并称为“海内三宝”。1992年被评为“北京旅游世界之最”，是国家4A级旅游区、市级风景名胜区，现已被列入世界文化遗产预备清单名录。 ",
                "callLine":"010-61389604",
                "weixin2wm":"images/",
                "daolanImg":"images/yunjs-dl.png",
                "daolanpoint":[
                    {   
                        "sceneName":"scene_59421",
                        "left":"48.17%",
                        "top":"93.67%",
                        "lock":true
                    },{
                        "sceneName":"scene_59399",
                        "left":"48.17%",
                        "top":"80.29%",
                        "lock":true
                    },{
                        "sceneName":"scene_59400",
                        "left":"48.17%",
                        "top":"72.15%",
                        "lock":true
                    },{
                         "sceneName":"scene_59408",
                        "left":"48.17%",
                        "top":"64.01%",
                        "lock":true
                    },{
                        "sceneName":"scene_59410",
                        "left":"48.17%",
                        "top":"56.24%",
                        "lock":true
                    },{
                        "sceneName":"scene_59418",
                        "left":"48.17%",
                        "top":"50.27%",
                        "lock":true
                    },{
                        "sceneName":"scene_59419",
                        "left":"48.17%",
                        "top":"42.86%",
                        "lock":true
                    },{
                        "sceneName":"scene_59424",
                        "left":"71.67%",
                        "top":"45.93%",
                        "lock":true
                    },{
                        "sceneName":"scene_59403",
                        "left":"87.33%",
                        "top":"45.93%",
                        "lock":true
                    },{
                        "sceneName":"scene_59390",
                        "left":"73.83%",
                        "top":"34.72%",
                        "lock":true
                    },{
                       "sceneName":"scene_59393",
                        "left":"29.17%",
                        "top":"36.17%",
                        "lock":true
                    },{
                       "sceneName":"scene_59387",
                        "left":"48.17%",
                        "top":"17.36%",
                        "lock":true
                    },{
                       "sceneName":"scene_59405",
                        "left":"14.67%",
                        "top":"50.27%",
                        "lock":true
                    },{
                       "sceneName":"scene_59422",
                        "left":"29.17%",
                        "top":"83.18%",
                        "lock":true
                    },
                ]
            },
            "nav3":{
                "name":"孤山寨",
                "logoBox":"images/logo1",
                "introductionText":"孤山寨位于十渡风景名胜区七渡村南，是十渡风景名胜区内最著名的一条大峡谷，深约10公里。步入峡谷，两侧山峰林立，怪石嶙峋，越向里走，山势越险峻，峡谷越窄，最窄处仅为5米；越向里走，植被越丰茂，景致越幽美。",
                "callLine":"010-61349871",
                "weixin2wm":"images/",
                "daolanImg":"images/gushzh-dl.png",
                "daolanpoint":[
                    {
                       "sceneName":"scene_59429",
                        "left":"7.27%",
                        "top":"45.11%",
                        "lock":true
                    },{
                       "sceneName":"scene_59507",
                        "left":"8.06%",
                        "top":"29.11%",
                        "lock":true
                    },{
                       "sceneName":"scene_59483",
                        "left":"16.43%",
                        "top":"38.67%",
                        "lock":true
                    },{
                       "sceneName":"scene_59477",
                        "left":"30.17%",
                        "top":"38.25%",
                        "lock":true
                    },{
                       "sceneName":"scene_59457",
                        "left":"21.96%",
                        "top":"30.15%",
                        "lock":true
                    },{
                       "sceneName":"scene_59480",
                        "left":"41.55%",
                        "top":"34.51%",
                        "lock":true
                    },{
                       "sceneName":"scene_59469",
                        "left":"48.66%",
                        "top":"38.25%",
                        "lock":true
                    },{
                       "sceneName":"scene_59466",
                        "left":"57.82%",
                        "top":"33.47%",
                        "lock":true
                    },{
                       "sceneName":"scene_59504",
                        "left":"57.82%",
                        "top":"51.98%",
                        "lock":true
                    },{
                       "sceneName":"scene_59526",
                        "left":"49.92%",
                        "top":"56.34%",
                        "lock":true
                    },{
                       "sceneName":"scene_59523",
                        "left":"68.72%",
                        "top":"34.51%",
                        "lock":true
                    },{
                       "sceneName":"scene_59512",
                        "left":"71.56%",
                        "top":"20.17%",
                        "lock":true
                    },
                ]
            },"nav4":{
                "name":"八渡天禄山水上乐园",
                "logoBox":"images/logo1",
                "introductionText":"十渡风景区位于北京市房山区十渡镇和张坊镇，距市区92公里，是距首都最近、华北地区最大、最典型的岩溶峰林峡谷，有飞来石、龙山“佛”字、石中石等12大地质奇观，享有“青山野渡、百里画廊”之美誉。拒马河蜿蜒迂回，穿山而过，宛如一条玉带，与峰林映衬，相得益彰。山水景物既有中国北方之雄奇，又有江南水乡之柔媚。1986年被评为北京新十六景之一，1999年被评为北京市首批风景名胜区，为国家4A级旅游景区，2004年被批准为国家地质公园。",
                "callLine":"010-61349871",
                "weixin2wm":"images/",
                "daolanImg":"images/badu-dl.png",
                "daolanpoint":[
                    {
                       "sceneName":"scene_59627",
                        "left":"68.18%",
                        "top":"84.56%",
                        "lock":true
                    },{
                       "sceneName":"scene_59625",
                        "left":"73.32%",
                        "top":"45.59%",
                        "lock":true
                    },{
                       "sceneName":"scene_59629",
                        "left":"63.04%",
                        "top":"34.01%",
                        "lock":true
                    },{
                       "sceneName":"scene_59638",
                        "left":"43.68%",
                        "top":"61.58%",
                        "lock":true
                    },
                ]
            },"nav5":{
                "name":"十渡拒马乐园",
                "logoBox":"images/logo1",
                "introductionText":"拒马乐园位于十渡风景区内，这里河宽水清，山势险峻，步步皆景，四季如画，以“幽、古、秀、谜、惊、险、奇、特”引誉中华，是一处闻名遐尔的旅游胜地。北京拒马娱乐有限公司不断开拓创新，先后从加拿大、新西兰、美国、奥地利引进了具有都市休闲特点的娱乐项目，第一个将勇敢者的游戏——蹦极跳引入中国，落户十渡，引发了全国范围内的蹦极热，被誉为“十渡蹦极，神州第一”，现已形成了一个集休闲、娱乐、野趣、餐饮、住宿于一体的大型、综合游乐园。",
                "callLine":"010-61349871",
                "weixin2wm":"images/",
                "daolanImg":"images/shidu-dl.png",
                "daolanpoint":[
                    {
                       "sceneName":"scene_59463",
                        "left":"19.60%",
                        "top":"30.70%",
                        "lock":true
                    },{
                       "sceneName":"scene_59601",
                        "left":"32.28%",
                        "top":"22.98%",
                        "lock":true
                    },{
                       "sceneName":"scene_59535",
                        "left":"48.12%",
                        "top":"25.55%",
                        "lock":true
                    },{
                       "sceneName":"scene_59579",
                        "left":"40.99%",
                        "top":"16.18%",
                        "lock":true
                    },{
                       "sceneName":"scene_59570",
                        "left":"51.29%",
                        "top":"39.71%",
                        "lock":true
                    },{
                       "sceneName":"scene_59584",
                        "left":"51.29%",
                        "top":"51.84%",
                        "lock":true
                    },{
                       "sceneName":"scene_59577",
                        "left":"45.54%",
                        "top":"62.50%",
                        "lock":true
                    },{
                       "sceneName":"scene_59602",
                        "left":"34.46%",
                        "top":"71.14%",
                        "lock":true
                    },{
                       "sceneName":"scene_59597",
                        "left":"60.00%",
                        "top":"74.08%",
                        "lock":true
                    },{
                       "sceneName":"scene_59537",
                        "left":"63.96%",
                        "top":"65.81%",
                        "lock":true
                    },{
                       "sceneName":"scene_59546",
                        "left":"66.53%",
                        "top":"56.43%",
                        "lock":true
                    },{
                       "sceneName":"scene_59599",
                        "left":"79.80%",
                        "top":"65.81%",
                        "lock":true
                    },{
                       "sceneName":"scene_59603",
                        "left":"78.42%",
                        "top":"50.92%",
                        "lock":true
                    },{
                       "sceneName":"scene_59566",
                        "left":"64.55%",
                        "top":"13.79%",
                        "lock":true
                    },{
                       "sceneName":"scene_59574",
                        "left":"82.77%",
                        "top":"34.56%",
                        "lock":true
                    }
                ]
            },"nav6":{
                "name":"十五渡东湖港",
                "logoBox":"images/logo1",
                "introductionText":"东湖港地处十渡风景名胜区内十五渡，与野三坡毗邻，距北京市区101公里，是绿色旅游和度假的胜地。<br />东湖港有“幽谷叠瀑，檀林氧吧”的美誉。经铁索桥进入景区，翠绿的檀林，蜿蜒的千年古藤遍布整个峡谷，古老而神秘。奇特的“三叠瀑布”水流分三叠落差，直流急下，瀑水入潭击石飞溅。“华北第一梯”倚峭而建，工程险峻，有“登云梯，而览群山”之势。回音壁瀑布是东湖港著名的景观之一，高瀑飞银，直泄潭底，水势猛烈。<br />这里自然资源丰富、动植物种类繁多，生机盎然妙趣横生。领略了东湖港自然天成的妙趣后，游客们可在秀丽的拒马河上荡筏滑艇，嬉水摸鱼,增添了游玩中的乐趣，享受酷暑中的凉意。这里还设有沙滩浴场和沙滩排球以及情侣小屋，是聚会野餐的最佳场所。",
                "callLine":"010-61349871",
                "weixin2wm":"images/",
                "daolanImg":"images/donghg-dl.png",
                "daolanpoint":[
                    {
                       "sceneName":"scene_59425",
                        "left":"48.02%",
                        "top":"39.89%",
                        "lock":true
                    },{
                       "sceneName":"scene_59525",
                        "left":"42.62%",
                        "top":"61.95%",
                        "lock":true
                    },{
                       "sceneName":"scene_59521",
                        "left":"61.12%",
                        "top":"96.14%",
                        "lock":true
                    },{
                       "sceneName":"scene_59458",
                        "left":"52.60%",
                        "top":"94.12%",
                        "lock":true
                    },{
                       "sceneName":"scene_59517",
                        "left":"70.06%",
                        "top":"88.05%",
                        "lock":true
                    },{
                       "sceneName":"scene_59465",
                        "left":"52.60%",
                        "top":"73.71%",
                        "lock":true
                    },{
                       "sceneName":"scene_59508",
                        "left":"42.20%",
                        "top":"21.51%",
                        "lock":true
                    },{
                       "sceneName":"scene_59494",
                        "left":"54.26%",
                        "top":"14.34%",
                        "lock":true
                    },{
                       "sceneName":"scene_59497",
                        "left":"83.16%",
                        "top":"28.49%",
                        "lock":true
                    },{
                       "sceneName":"scene_59474",
                        "left":"80.67%",
                        "top":"36.21%",
                        "lock":true
                    },{
                       "sceneName":"scene_59467",
                        "left":"59.46%",
                        "top":"41.73%",
                        "lock":true
                    },{
                       "sceneName":"scene_59513",
                        "left":"63.83%",
                        "top":"46.69%",
                        "lock":true
                    },{
                       "sceneName":"scene_59490",
                        "left":"72.77%",
                        "top":"48.16%",
                        "lock":true
                    },{
                       "sceneName":"scene_59492",
                        "left":"22.45%",
                        "top":"32.90%",
                        "lock":true
                    },
                ]
            },"nav7":{
                "name":"周口店北京猿人遗址博物馆",
                "logoBox":"images/logo1",
                "introductionText":"周口店北京人遗址位于房山区周口店镇龙骨山上，距市区43公里，是闻名中外的古人类文化遗址。北京人头盖骨和大量用火证据的发掘，为研究人类进化提供了生动有力的实证。1961年被列为第一批全国重点文物保护单位，1987年被列入世界文化遗产名录，1992年被评为北京旅游世界之最，1997年被列为全国百家爱国主义教育基地，2009年被评为新北京十六景，为国家4A级旅游景区。周口店北京人遗址博物馆新馆于2014年5月18日对外开放。新馆采取基本陈列、临时陈列和遗址展示相结合的展陈体系，使用“实物展陈与互动体验相结合、文物展示与场景再现相结合、传统展陈与数字技术相结合”的表现手段，从“发现、研究、保护”三个层面对周口店遗址进行全面、系统的展示。在这里你不仅可以感受到远古的神秘和火的文明，还能体会到历史的厚重与沧桑的变迁，理解根祖文明的魅力所在。",
                "callLine":"010-53230035",
                "weixin2wm":"images/",
                "daolanImg":"images/zhoukd-dl.png",
                "daolanpoint":[
                    {
                       "sceneName":"scene_58045",
                       "left":"86.17%",
                       "top":"50.00%",
                        "lock":true
                    },{
                       "sceneName":"scene_58042",
                        "left":"84.00%",
                        "top":"57.92%",
                        "lock":true
                    },{
                       "sceneName":"scene_58031",
                        "left":"83.00%",
                        "top":"66.39%",
                        "lock":true
                    },{
                       "sceneName":"scene_58048",
                        "left":"79.67%",
                        "top":"61.48%",
                        "lock":true
                    },{
                       "sceneName":"scene_58028",
                        "left":"74.67%",
                        "top":"63.39%",
                        "lock":true
                    },{
                       "sceneName":"scene_58043",
                        "left":"73.17%",
                        "top":"72.40%",
                        "lock":true
                    },{
                       "sceneName":"scene_58026",
                        "left":"79.00%",
                        "top":"72.40%",
                        "lock":true
                    },
                ]
            },"nav8":{
                "name":"石花洞",
                "logoBox":"images/logo1",
                "introductionText":"石花洞位于北京市房山区河北镇，距市区46公里。石花洞又名潜真洞、石佛洞，被评为“中国溶洞最佳奇观”。石花洞风景区是华北地区岩溶洞穴的典型代表，被专家评价为中国罕见的多层洞、岩溶景观最丰富的溶洞。石花洞以天然形成的石花得名，石花形式繁多，异彩纷呈，数量庞大，为国内洞穴之最。石花洞的总体特征是洞体多层多支，从上到下共七层，每层景观各不相同，分人文趣味层、探奇观赏层等，其中由月奶石形成的“石莲花”，由540余片石钟乳组成的高10米、长18米的石幔，以及石旗、双彩石盾、龙宫双柱等景观都是中外洞穴岩溶景观精品。石花洞被评为国家重点风景名胜区、国家地质公园、国家4A级旅游景区。",
                "callLine":"010-60312170",
                "weixin2wm":"images/",
                "daolanImg":"images/shihd-dl.png",
                "daolanpoint":[
                    {
                       "sceneName":"scene_58052",
                        "left":"81.83%",
                        "top":"24.81%",
                        "lock":true
                    }, {
                       "sceneName":"scene_58016",
                        "left":"74.50%",
                        "top":"24.81%",
                        "lock":true
                    }, {
                       "sceneName":"scene_58019",
                        "left":"62.67%",
                        "top":"30.74%",
                        "lock":true
                    }, {
                       "sceneName":"scene_58021",
                        "left":"43.67%",
                        "top":"29.63%",
                        "lock":true
                    }, {
                       "sceneName":"scene_58025",
                        "left":"31.17%",
                        "top":"27.04%",
                        "lock":true
                    }, {
                       "sceneName":"scene_58029",
                        "left":"24.67%",
                        "top":"54.07%",
                        "lock":true
                    }, {
                       "sceneName":"scene_58032",
                        "left":"33.33%",
                        "top":"61.48%",
                        "lock":true
                    }, {
                       "sceneName":"scene_58037",
                        "left":"13.00%",
                        "top":"55.56%",
                        "lock":true
                    }, {
                       "sceneName":"scene_58040",
                        "left":"72.33%",
                        "top":"43.33%",
                        "lock":true
                    }, {
                       "sceneName":"scene_58041",
                        "left":"45.50%",
                        "top":"47.78%",
                        "lock":true
                    }, {
                       "sceneName":"scene_58044",
                        "left":"62.67%",
                        "top":"48.15%",
                        "lock":true
                    }, {
                       "sceneName":"scene_58049",
                        "left":"53.67%",
                        "top":"29.63%",
                        "lock":true
                    }, {
                       "sceneName":"scene_58050",
                        "left":"26.83%",
                        "top":"39.26%",
                        "lock":true
                    }, {
                       "sceneName":"scene_58051",
                        "left":"49.33%",
                        "top":"64.44%",
                        "lock":true
                    }, 
                ]
            },"nav9":{
                "name":"圣莲山",
                "logoBox":"images/logo1",
                "introductionText":"圣莲山风景区位于北京市房山区史家营乡，距市区86公里，原名“圣米石塘”，是早时“京畿八景”之一。圣莲山海拔930米，山上有始建于民国13年的道教名观蟠桃宫，有建于大明永乐年间的佛教名寺胜泉寺，还有民国时期曹锟、吴佩孚、杨小楼等在此修建的别墅群。山上天然溶洞圣水洞中的泉水，常年滴水犹如琴瑟之韵，传说大清皇帝乾隆曾派人取水养生。圣莲山现为道教宗教活动场所，建有57米高老子像、观拜台、真武观、逍遥谷、道教养生馆，是一处集人文景观与自然景观于一体的旅游、观光胜地。",
                "callLine":"010-60319023",
                "weixin2wm":"images/",
                "daolanImg":"images/shenglsh-dl.png",
                "daolanpoint":[
                    {
                       "sceneName":"scene_59645",
                        "left":"49.67%",
                        "top":"61.46%",
                        "lock":true
                    },{
                       "sceneName":"scene_59647",
                        "left":"47.50%",
                        "top":"42.57%",
                        "lock":true
                    },{
                       "sceneName":"scene_59648",
                        "left":"24.50%",
                        "top":"84.63%",
                        "lock":true
                    },{
                       "sceneName":"scene_59649",
                        "left":"28.83%",
                        "top":"66.25%",
                        "lock":true
                    },{
                       "sceneName":"scene_59650",
                        "left":"36.17%",
                        "top":"48.87%",
                        "lock":true
                    },{
                       "sceneName":"scene_59619",
                        "left":"87.67%",
                        "top":"22.92%",
                        "lock":true
                    },{
                       "sceneName":"scene_59621",
                        "left":"81.33%",
                        "top":"20.91%",
                        "lock":true
                    },{
                       "sceneName":"scene_59641",
                        "left":"57.83%",
                        "top":"55.92%",
                        "lock":true
                    },{
                       "sceneName":"scene_59628",
                        "left":"66.67%",
                        "top":"44.84%",
                        "lock":true
                    }, 
                ]
            },"nav10":{
                "name":"百花山自然风景区",
                "logoBox":"images/logo1",
                "introductionText":"百花山风景区位于北京市房山区史家营乡莲花庵，距市区89公里，乘车走108国道经史家营可直达山顶，总面积819公顷，海拔1991米。百花山的地文资源奇特，“天然长城”、“母子石”、“震山石—锦簇攒天”、“驼峰”、“文殊像”等均具有较高的科学价值和观赏度；百花山的气象景观婀娜多姿，云海云雾是百花山最多见的胜景。当夜幕降临，游客在山顶还可以远眺京城万家灯火；百花山夏季气候凉爽，空气新鲜，无蚊虫叮咬，无噪音干扰，自古就是避暑休闲的绝好胜地。",
                "callLine":"010-60390257",
                "weixin2wm":"images/",
                "daolanImg":"images/baihsh-dl.png",
                "daolanpoint":[
                    {
                       "sceneName":"scene_59423",
                        "left":"39.33%",
                        "top":"28.68%",
                        "lock":true
                    },{
                       "sceneName":"scene_59663",
                        "left":"76.33%",
                        "top":"62.02%",
                        "lock":true
                    },{
                       "sceneName":"scene_59437",
                        "left":"26.17%",
                        "top":"11.37%",
                        "lock":true
                    },{
                       "sceneName":"scene_59409",
                        "left":"30.33%",
                        "top":"9.04%",
                        "lock":true
                    },{
                       "sceneName":"scene_59413",
                        "left":"22.67%",
                        "top":"17.57%",
                        "lock":true
                    },
                ]
            },"nav11":{
                "name":"白草畔自然风景区",
                "logoBox":"images/logo1",
                "introductionText":"白草畔风景区位于北京市房山区霞云岭乡四马台村，距市区111公里。景区面积19.2平方公里,林木覆盖率82％，海拔最低处也比城区高800多米。以白草畔2161米的主峰为中心，一条西北至东南向平缓开阔的山脊面，组成北京地区面积最大、平均海拔最高的亚高山草甸。这里生长着290多种花草，40多种灌木，一年三季百花盛开，清香四溢。景区以百花争艳的高山草甸景观为特点，拥有丰富的奇花异草、野果山菜，树木繁多，百花争妍，尤以大片丁香花为奇。在丁香花开放的季节，满谷花香，直飘至数十里外。景区内有鲲鹏峡谷、高坪百草、神洞仙道三大景点和山上八景、山下八景。<br />白草畔空气清新，环境幽美，集森林、石林、甘泉、珍稀植物、野生动物、云海日出等景观于一体。气候凉爽宜人，夏季气温比北京城区低8-16度，是炎热的夏季旅游度假的佳处所在。",
                "callLine":"010-60369038",
                "weixin2wm":"images/",
                "daolanImg":"images/baicp-dl.png",
                "daolanpoint":[
                    {
                       "sceneName":"scene_59447",
                        "left":"39.00%",
                        "top":"28.08%",
                        "lock":true
                    },{
                       "sceneName":"scene_59443",
                        "left":"17.50%",
                        "top":"20.40%",
                        "lock":true
                    },{
                       "sceneName":"scene_59445",
                        "left":"13.17%",
                        "top":"18.18%",
                        "lock":true
                    },{
                       "sceneName":"scene_59451",
                        "left":"11.00%",
                        "top":"23.84%",
                        "lock":true
                    },{
                       "sceneName":"scene_59412",
                        "left":"65.67%",
                        "top":"90.71%",
                        "lock":true
                    },{
                       "sceneName":"scene_59452",
                        "left":"23.67%",
                        "top":"17.98%",
                        "lock":true
                    },{
                       "sceneName":"scene_59430",
                        "left":"29.67%",
                        "top":"23.84%",
                        "lock":true
                    },{
                       "sceneName":"scene_59426",
                        "left":"34.00%",
                        "top":"27.27%",
                        "lock":true
                    },{
                       "sceneName":"scene_59436",
                        "left":"28.00%",
                        "top":"33.74%",
                        "lock":true
                    },{
                       "sceneName":"scene_59441",
                        "left":"6.50%",
                        "top":"27.07%",
                        "lock":true
                    },{
                       "sceneName":"scene_59396",
                        "left":"4.33%",
                        "top":"30.51%",
                        "lock":true
                    },
                ]
            },"nav12":{
                "name":"世界地质公园博物馆",
                "logoBox":"images/logo1",
                "introductionText":"中国房山世界地质公园博物馆位于房山区长沟镇，占地面积91.65亩，总建筑面积10000平方米，博物馆于2009年3月29日奠基，2010年5月15日开馆。博物馆建筑设计立意“石破天惊”，整体建筑顺应自然地势、演绎造山运动、隐喻人类起源、应用地域材料，充分体现了“尊重自然机理、活用原生地形、造型自然舒展、内外空间一致”的特点，具有唯一性和典型性。<br />博物馆具有科普教育、休闲旅游、地质研究、宣传展示、信息交流五大功能。馆内设有开篇厅、地史演化厅、八大园区厅、国内外世界地质公园展厅、实物标本厅、展望厅六大展厅，以及4D影院和报告厅，同时还有科研科普中心、游客服务中心等。馆外设有科普广场，有大型标本和地学名人雕塑。",
                "callLine":"010-61368202",
                "weixin2wm":"images/",
                "daolanImg":"images/dizhigy-dl.png",
                "daolanpoint":[
                    {
                       "sceneName":"scene_58035",
                        "left":"89.50%",
                        "top":"86.74%",
                        "lock":true
                    },{
                       "sceneName":"scene_58030",
                        "left":"47.83%",
                        "top":"61.67%",
                        "lock":true
                    },{
                       "sceneName":"scene_58038",
                        "left":"14.67%",
                        "top":"39.77%",
                        "lock":true
                    },{
                       "sceneName":"scene_58033",
                        "left":"16.83%",
                        "top":"23.63%",
                        "lock":true
                    },{
                       "sceneName":"scene_58015",
                        "left":"30.67%",
                        "top":"28.24%",
                        "lock":true
                    },{
                       "sceneName":"scene_58020",
                        "left":"39.83%",
                        "top":"33.14%",
                        "lock":true
                    },{
                       "sceneName":"scene_58024",
                        "left":"52.17%",
                        "top":"35.16%",
                        "lock":true
                    },{
                       "sceneName":"scene_58017",
                        "left":"69.83%",
                        "top":"42.65%",
                        "lock":true
                    },{
                       "sceneName":"scene_58023",
                        "left":"56.50%",
                        "top":"47.26%",
                        "lock":true
                    },{
                       "sceneName":"scene_58027",
                        "left":"45.67%",
                        "top":"44.67%",
                        "lock":true
                    },
                ]
            },"nav13":{
                "name":"上方山森林公园",
                "logoBox":"images/logo1",
                "introductionText":"上方山国家森林公园位于北京市房山区韩村河镇，距市区58公里，是全国二十家重点示范国家森林公园之一。早在东魏时期，就有僧人在上方山开山、筑寺、修路、种树。经历代增建修葺，到明代这里已成为“幽燕古奥室，兜率居中岩，花宫七十二，上下东西嵌”的宏伟格局。历代名人、文人墨客咏诗作画，修庙建亭，形成了桥、亭、庙、阁、洞、石、峰、林融为一体的宗教风景胜地，历史上就有“南有苏杭，北有上方”之说。著名景观有：以云水洞为代表的九大洞穴、以兜率寺为代表的72座寺庙、以摘星坨为代表的12座山峰、以菩提树为代表的四大树王，以及《智取华山》外景地、云梯、天坑、四十二章经等景观。",
                "callLine":"010-61315309",
                "weixin2wm":"images/",
                "daolanImg":"images/shangfsh-dl.png",
                "daolanpoint":[
                    {
                       "sceneName":"scene_59609",
                        "left":"72.67%",
                        "top":"79.65%",
                        "lock":true
                    },{
                       "sceneName":"scene_59667",
                        "left":"61.33%",
                        "top":"84.00%",
                        "lock":true
                    },{
                       "sceneName":"scene_59624",
                        "left":"68.33%",
                        "top":"61.91%",
                        "lock":true
                    },{
                       "sceneName":"scene_59527",
                        "left":"74.83%",
                        "top":"53.91%",
                        "lock":true
                    },{
                       "sceneName":"scene_59614",
                        "left":"89.83%",
                        "top":"47.48%",
                        "lock":true
                    },{
                       "sceneName":"scene_59553",
                        "left":"52.50%",
                        "top":"47.30%",
                        "lock":true
                    },{
                       "sceneName":"scene_59618",
                        "left":"27.83%",
                        "top":"31.83%",
                        "lock":true
                    },{
                       "sceneName":"scene_59655",
                        "left":"7.67%",
                        "top":"31.83%",
                        "lock":true
                    },{
                       "sceneName":"scene_59657",
                        "left":"23.50%",
                        "top":"71.65%",
                        "lock":true
                    },{
                       "sceneName":"scene_59596",
                        "left":"19.17%",
                        "top":"18.61%",
                        "lock":true
                    },{
                       "sceneName":"scene_59616",
                        "left":"23.50%",
                        "top":"81.22%",
                        "lock":true
                    },
                ]
            },"nav14":{
                "name":"银狐洞",
                "logoBox":"images/logo1",
                "introductionText":"银狐洞位于北京市房山区佛子庄乡，是石花洞国家重点风景名胜区、国家地质公园的景区之一，是中国华北地区唯一开放的水旱洞为一体的自然风景溶洞。洞内石塔、石柱、石花、石笋等景观丰富，尤其是洞顶倒挂着长近2米、由雪白方解石晶体形成的银狐，脸似雪豹、身似银狐、冰雕玉琢、举世无双，堪称“中华国宝”。洞内有条1000米的地下暗河，可戏水泛舟，被称为“华北地下迷宫”。河水清澈见底，水中含有人体所必需的多种微量元素，具有神奇的医疗作用。",
                "callLine":"010-60363236",
                "weixin2wm":"images/",
                "daolanImg":"images/yinhd-dl.png",
                "daolanpoint":[
                    {
                       "sceneName":"scene_59642",
                        "left":"24.50%",
                        "top":"20.85%",
                        "lock":true
                    },{
                       "sceneName":"scene_59644",
                        "left":"14.17%",
                        "top":"11.18%",
                        "lock":true
                    },{
                       "sceneName":"scene_59646",
                        "left":"33.00%",
                        "top":"32.02%",
                        "lock":true
                    },{
                       "sceneName":"scene_59617",
                        "left":"40.33%",
                        "top":"25.68%",
                        "lock":true
                    },{
                       "sceneName":"scene_59626",
                        "left":"64.17%",
                        "top":"34.14%",
                        "lock":true
                    },{
                       "sceneName":"scene_59622",
                        "left":"50.17%",
                        "top":"30.51%",
                        "lock":true
                    },{
                       "sceneName":"scene_59632",
                        "left":"26.67%",
                        "top":"34.14%",
                        "lock":true
                    },{
                       "sceneName":"scene_59635",
                        "left":"76.67%",
                        "top":"54.08%",
                        "lock":true
                    },{
                       "sceneName":"scene_59640",
                        "left":"43.67%",
                        "top":"41.09%",
                        "lock":true
                    },
                ]
            },
        }
